### ISSUE TITLE
Snippets aren't visible in Jupyter Notebook

### ISSUE THREAD

**Issue by vaishnavsudarshan** [sagemathinc/cocalc-snippets#24]
In this page, [https://doc.cocalc.com/snippets.html#system-wide-snippets](url), it says Snippets are in Jupyter Notebook. However, I cannot see them. 
![image](https://github.com/sagemathinc/cocalc-snippets/assets/134876525/57d78ee2-03fa-49c8-812e-38365a8ac93f)

I see them in the Sage Math worksheet. 
![image](https://github.com/sagemathinc/cocalc-snippets/assets/134876525/5368d0cc-8e1b-44d8-89b4-835c0201c079)
Could you please add Snippets back into Jupyter Notebook?

**Comment by williamstein** [comment]
Click on the ... ellipses in the top right of the first screenshot.
